wandb_version: 1

batch_size:
  desc: null
  value: 10
n_token:
  desc: null
  value: 200
n_epoch:
  desc: null
  value: 50
eval_interval:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0003
eval_iters:
  desc: null
  value: 10
split:
  desc: null
  value: 0.9
n_embd:
  desc: null
  value: 10
dim_feedforward:
  desc: null
  value: 100
n_head:
  desc: null
  value: 2
n_layer:
  desc: null
  value: 2
n_bin:
  desc: null
  value: 10
dropout:
  desc: null
  value: 0.5
min_counts_genes:
  desc: null
  value: 10
seed:
  desc: null
  value: 1234
dataset:
  desc: null
  value: data/Pancreas/endocrinogenesis_day15.h5ad
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684915756.323974
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.11.3
      5: 0.15.3
      8:
      - 5
