wandb_version: 1

epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0003
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684913785.71105
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.11.3
      5: 0.15.3
      8:
      - 5
