program: /home/claassen/cxb257/scTransformer/src/trainer_cluster.py
method: grid
metric:
  name: test_loss
  goal: minimize
parameters:
    n_epoch:
        value: 50
    mlm_probability:
        value: 5
    n_bin:
        value: 100
    n_token:
        value: 200
    n_emb:
        value: 128
    n_head:
        value: 4
    dim_feedforward:
        value: 32
    n_layer:
        value: 4
    batch_size:
        value: 128
    cell_type:
        value: 'None'
    mask_type:
        value: 'src_key_padding_mask'
    randomization:
        value: False
    tissue:
        value: 'heart endothelial'
    do_preprocessing:
        value: False
    extern_testset:
        value: False