program: /home/claassen/cxb257/scTransformer/src/trainer_cluster.py
method: grid
metric:
  name: test_loss
  goal: minimize
parameters:
    n_epoch:
        value: 10
    mlm_probability:
        value: 3
    n_bin:
        value: 20
    batch_size:
        value: 1
    cell_type:
        value: 'None'
    mask_type:
        value: 'attn_mask'
    randomization:
        value: True
