program: /home/claassen/cxb257/scTransformer/src/trainer_finetune.py
method: grid
metric:
  name: test_loss
  goal: minimize
parameters:
    learning_rate:
        value: 1e-4
    n_epoch:
        value: 100
    mlm_probability:
        value: 12
    n_bin:
        value: 100
    n_token:
        value: 200
    n_emb:
        value: 256
    n_head:
        value: 8
    dim_feedforward:
        value: 64
    n_layer:
        value: 4
    batch_size:
        value: 7
    cell_type:
        value: 'None'
    mask_type:
        value: 'src_key_padding_mask'
    randomization:
        value: False
    tissue:
        value: 'pmbc model fintuned for CD4 positive subset'
    do_preprocessing:
        value: True
    extern_testset:
        value: False