program: /home/claassen/cxb257/scTransformer/src/trainer_cluster.py
method: grid
metric:
  name: test_loss
  goal: minimize
parameters:
    n_epoch:
        value: 100
    mlm_probability:
        value: 0.15
    n_bin:
        value: 100
    n_token:
        value: 500
    n_emb:
        value: 512
    n_head:
        value: 8
    dim_feedforward:
        values: [32, 512]
    n_layer:
        values: [8, 12]
    batch_size:
        value: 16
    cell_type:
        value: 'None'
    mask_type:
        value: 'src_key_padding_mask'
    randomization:
        value: False
