program: /home/claassen/cxb257/scTransformer/src/trainer_cluster.py
method: grid
metric:
  name: test_loss
  goal: minimize
parameters:
    mlm_probability:
        value: 0.15
    n_token:
      value: 2
    n_bin:
        value : 100
    batch_size:
        value: 256
    cell_type:
        value: 'None'
    hvg_flavor:
        values: ['seurat', 'cell_ranger']
