program: /home/claassen/cxb257/scTransformer/src/trainer_cluster.py
method: grid
metric:
  name: test_loss
  goal: minimize
parameters:
    n_epoch:
        value: 2
    mlm_probability:
        value: 0.03
    n_bin:
        value: 100
    n_token:
        value: 1500
    n_emb:
        value: 256
    n_head:
        value: 8
    dim_feedforward:
        value: 64
    n_layer:
        value: 4
    batch_size:
        value: 11
    cell_type:
        value: 'None'
    mask_type:
        value: 'src_key_padding_mask'
    randomization:
        value: False
    tissue:
        value: 'heart1Mio / large model / 1500 token'
    do_preprocessing:
        value: False
    extern_testset:
        value: True